fix: createEvent type
testing-library/dom-testing-library pull request #776
Opened 2020-10-05 14:11 UTC by marcosvega91

fix #775

**What**: fix typescript type

**Why**: It was not correct, because you can create custom Event using `createEvent` function

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] Tests
- [X] Typescript definitions updated
- [X] Ready to be merged

2020-10-05 14:44 UTC, eps1lon requested changes
A test in `types/__tests__/type-tests.ts` would be nice.

2020-10-05 17:56 UTC, eps1lon approved these changes

2020-10-05 18:14 UTC, kentcdodds approved these changes
Thanks!

2020-10-05 18:15 UTC, merged

2020-10-12 10:09 UTC, eschaefer commented
@marcosvega91 this seems to have broken events like this in my tests:

```
fireEvent(
  document,
  new KeyboardEvent('keydown', { key: 'Backspace', code: 'Backspace' })
);
```

Looking into the cause, but until I know, I need to downgrade to `7.24.3`

2020-10-12 10:15 UTC, eps1lon commented
@eschaefer Please open a new issue and fill out as much as you can of the issue template. I cannot reproduce a type-related issue with your code: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgM2FApgUQG7oHbwC+KUEIcA5AAIzoDOMweA5gLQA2wARlAIZQBPAPQZeAYxgUAUFNQYc+GAAopcOABMIYgK4hFAGlVw86AO5wA0ugFcI-dQoJKKAa2ubTeCvsRw3AgC5KACFxFzowcXRvODEIdXQgilCxcMixaLhCAEopbIBuKSA