feat: add logPlaygroundUrl in screen
testing-library/dom-testing-library pull request #781
Opened 2020-10-12 13:57 UTC by balavishnuvj

Based on discussion at #780

2020-10-12 13:59 UTC, balavishnuvj commented
Do let me know what you think of this. This mostly PRd version of what @smeijer had suggested.

2020-10-12 15:03 UTC, marcosvega91 requested changes
Hi @balavishnuvj thanks for this implementation 💯 . I have added some comments

2020-10-12 15:03 UTC, marcosvega91 commented on src/screen.js
> +}
As for the previous comment. What do you think of this?

```suggestion
const logTestingPlaygroundURL = (element = getDocument().body) => {
  if ('innerHTML' in element) {
    if (element.innerHTML === '')
      console.log(
        `The provided element(${element.nodeName}) doesn't have any children.`,
      )
    console.log(`Open this URL in your browser\n\n${getPlaygroundUrl(element)}`)
  } else {
    console.log(`The element you're providing isn't a valid DOM element.`)
  }
}

2020-10-12 15:19 UTC, balavishnuvj commented
Hi @marcosvega91 , thank you reviewing so quick. Have addressed your concerns :)

2020-10-12 17:52 UTC, marcosvega91 submitted a review, later dismissed
Lgtm

2020-10-12 21:29 UTC, kentcdodds approved these changes
This is super! 👏 Just one little thing that I can merge myself. Thank you :)

2020-10-12 21:29 UTC, kentcdodds commented on src/__tests__/screen.js
> +  screen.logTestingPlaygroundURL(render('').container)
No need to render here:

```suggestion
  screen.logTestingPlaygroundURL(document.createElement('div'))
```

2020-10-12 21:34 UTC, kentcdodds reviewed
@marcosvega91 reminded me that we should do TS updates on this PR. You up for that @balavishnuvj?

2020-10-13 04:47 UTC, balavishnuvj commented
@kentcdodds I have tried to update the types. All the `t.ds` files were giving parsing error. So not sure if this defination works.

2020-10-13 15:12 UTC, merged

2020-10-13 18:29 UTC, balavishnuvj commented
@all-contributors please add @balavishnuvj for code