feat: Add extra error messages when `screen` was passed instead of a DOM element
testing-library/dom-testing-library pull request #949
Opened 2021-05-05 13:19 UTC by savcni01

The PR is fix #911 
When the user provides the wrong query (`screen` instead of a real query, we can output a clear, user-friendly error instead of general (and not relevant) - Create a new issue error.
**Checklist**:

- [ ] Documentation added to the "N/A"
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [ ] Typescript definitions updated "N/A"
- [x] Ready to be merged

2021-05-05 14:57 UTC, eps1lon commented on src/helpers.js
> +    node.debug instanceof Function &&
nit:
```suggestion
    typeof node.debug === 'function' &&
```
works as well? `instanceof` always looks sketchy.

2021-05-06 14:02 UTC, eps1lon requested changes

2021-05-06 14:02 UTC, eps1lon commented on src/helpers.js
> +    node.logTestingPlaygroundURL instanceof Function
```suggestion
    typeof node.logTestingPlaygroundURL === 'function'
```

2021-05-06 14:02 UTC, eps1lon commented on src/helpers.js
> +      `It looks like you used 'screen' object instead of one of selectors from screen.selectMethod and it passed a 'screen' instead of a DOM node. Did you do something like \`fireEvent.click(screen,
```suggestion
      `It looks like you passed a \`screen\` object. Did you do something like \`fireEvent.click(screen, ...\` when you meant to use a \`fireEvent.click(screen.getBy..., \`?`,
```

`screen.selectMethod` is probably too ambigious.

2021-05-10 08:11 UTC, merged

2021-05-10 08:11 UTC, eps1lon commented
@savcni01 Thanks!

2021-05-10 08:22 UTC, savcni01 commented
Thank you!